# Generated by Django 5.0.6 on 2024-08-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealkit', '0002_alter_chefplan_user_alter_company_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='mealkit',
            old_name='name',
            new_name='meal_name',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='name',
            new_name='plan_name',
        ),
    ]
