# Generated by Django 5.0.6 on 2024-08-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealkit', '0003_rename_name_company_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='customer_name',
        ),
    ]
