# Generated by Django 5.0.6 on 2024-08-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealkit', '0005_alter_giftcard_gift_amount_alter_giftcard_gift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='gift_amount',
            field=models.IntegerField(choices=[(70, '$70'), (140, '$140'), (280, '$280')]),
        ),
    ]
